# For Ubuntu only
language: cpp
os:
  - linux
compiler:
  - gcc
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install boost
  - travis_retry sudo apt-get install libcryptopp
script:
  - ./waf configure --with-tests
  - ./waf
  - ./waf install
  - ./build/unit-tests
# Tutorial for setting up notifications:
# http://docs.travis-ci.com/user/notifications/
# Here's a simple example for email notifications:
#
# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: [always|never|change] # default: change
#     on_failure: [always|never|change] # default: always
#
# There are also other types of notifications available, including:
# IRC, Campfire, Flowdock, HipChat, and Webhook.
# For more infomation about notifications, please visit the link above.
